[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = admin
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo_dev_pwd
db_name = odoo
; demo data: leave blank so modules load demo. Set to "all" to disable.
without_demo =
list_db = True
xmlrpc_port = 8069
